20 security scan of the image
N5GEH/n5geh.tools.mqtt-gateway pull request #288
Opened 2024-07-25 10:28 UTC by Bhavdeep13

2024-07-30 09:02 UTC, djs0109 requested changes

2024-07-30 09:02 UTC, djs0109 commented on Snyk/scan_results/eclipse-mosquitto_2.0.14.md
@Bhavdeep13 can you remove the scan results of extern image? Imop, only `gateway`, `api`, and maybe `frontend` need to stay

2024-07-30 10:25 UTC, Bhavdeep13 commented on Snyk/scan_results/eclipse-mosquitto_2.0.14.md
Ohh okay i’ll update it.

2024-07-30 10:28 UTC, Bhavdeep13 commented on Snyk/scan_results/eclipse-mosquitto_2.0.14.md
I kept all of them because with this manual script we don’t have to specify path of the docker images. It directly collects all the docker images and creates a file for that.

now if we again run it next time it will try to collect all images, maybe if we just want to scan frontend, gateway, api only then i can modify it and give specific path so that those images are only scanned

2024-08-06 09:29 UTC, Bhavdeep13 commented on Snyk/scan_results/eclipse-mosquitto_2.0.14.md
Done I have updated the files

2024-09-02 12:54 UTC, djs0109 approved these changes

2024-09-02 12:55 UTC, merged